/**
 * AI Service for Gemini API Integration
 */

/**
 * Sends a message to the Google Gemini API with the given system prompt.
 * Uses the gemini-1.5-flash model via REST API.
 * 
 * @param {string} userMessage - The message written by the user.
 * @param {string} systemPrompt - The formatted system prompt containing context.
 * @returns {Promise<string>} The AI's response text.
 */
export async function askGemini(userMessage, systemPrompt) {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  
  if (!apiKey) {
    throw new Error("Gemini API key (VITE_GEMINI_API_KEY) is not set in .env");
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

  // Format required by Gemini API v1beta
  const payload = {
    system_instruction: {
      parts: { text: systemPrompt }
    },
    contents: [
      {
        role: "user",
        parts: [{ text: userMessage }]
      }
    ]
  };

  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error("Gemini API Error Response:", errorData);
      throw new Error(`API Error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    
    // Extract the text from the response
    if (data.candidates && data.candidates.length > 0) {
      return data.candidates[0].content.parts[0].text;
    } else {
      throw new Error("No response generated by AI.");
    }
  } catch (error) {
    console.error("askGemini Error:", error);
    throw error;
  }
}
